### ISSUE TITLE
have forked and added some functionality, wondering if you would like to merge it into your original project...

### ISSUE THREAD

**Issue by JonathanMair** [pelican-plugins/pandoc-reader#27]
Hi - Many thanks for this great plugin!

I have been exploring Pelican as a basis for a personal website (mine) and I found this plugin, mainly because I was looking for a way of handling references. I have used pandoc in other contexts so I was very happy to see your plugin. 

However, I found it limited for my use case in that currently the only way of adding bibliographies is to add one for each file that needs references. I wanted to add the option to specify bibliography files and csl files on a per page and whole-site basis. 

I think I've got it working ok, and explain in the readme what it does: https://github.com/JonathanMair/pelican-academic-bibliographies-plugin 

Apart from these small changes I don't plan to make any other changes so I thought I'd flag them in case you'd be interested in merging them into your project, if so let me know if you want me to make a pull request or how you'd like to go about it. 

Thanks again,

Jon

**Comment by nandac** [comment]
Thanks @JonathanMair looks like a great feature to add especially in cases where the same references are needed for multiple blogs/pages.

Please make a pull request so that I can see what changes are required.

Do you have a test .md file to test the feature?

**Comment by JonathanMair** [comment]
Great.

I have provided some test files here: 

https://github.com/JonathanMair/Pelican-Pandoc-Samples

I used it to revive my ancient blog, most of the references are hardcoded still, but you can see it in action on this page: 

https://www.jonathanmair.com/pages/publications/

All the best, Jon

**Comment by nandac** [comment]
@JonathanMair After careful consideration, I do not think this is a feature I should add to the plugin because it seems to be more of a limitation with Pandoc's handling of bibliographies than with my plugin.

Although it is possible to add a bibliography in a defaults file I do not think it is the right place to add one.

It is best to add a bibliography on the command line or a metadata block in your document and they will be combined by Pandoc. To have an alternative location for your bibliography you can use the `resource-path` field.

In addition, my plugin is a wrapper around Pandoc and does not add or support any functionality not provided by Pandoc.

I will be closing this issue and the pull-request.

**Comment by JonathanMair** [comment]
Hi Nandac —yes I understand, that's fair enough and thanks for looking at it in detail.
