### ISSUE TITLE
Status of org_pandoc_reader plugin

### ISSUE THREAD

**Issue by kdeldycke** [pelican-plugins/pandoc-reader#7]
I just stumbled upon the [`org_pandoc_reader` pelican plugin](https://github.com/jo-tham/org_pandoc_reader) in the mono-repo. It has not been updated in 5 years. I guess it was super-seeded by this new (and clean, and cool!) plugin.

Is one of the maintainer of this plugin can confirm we can safely declare `org_pandoc_reader` as obsolete? In which case I'll add a note in the [`pelican-plugins` monorepo](https://github.com/getpelican/pelican-plugins) too make its status clear.

**Comment by avaris** [comment]
For the record, that's for a different file type ([emacs org mode](https://orgmode.org)) while this one is limited to markdown flavors (at least that's what the readme claims).

**Comment by nandac** [comment]
@kdeldycke My two cents worth on this plugin would be to update it to the new format, and see how we could improve it by borrowing ideas from the pandoc_reader plugin.

Since it is a different format I think keeping it separate is a good idea. I do not know very much about the Org format so we would need someone who uses this format regularly to collaborate on any updates.

**Comment by kdeldycke** [comment]
I was suspecting the `org_pandoc_reader` was only a slight customization of the original `pandoc_reader` but its not.

I will close this issue. There is no point dedicating effort and resource trying to bring `org_pandoc_reader` back to life if there no longer any interest in it. Thanks @avaris and @nandac for the feedback! 👍
